// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5tH6gn3ei_5okJvK247g8JxGaoYGBFrU',
    appId: '1:221351849206:web:af13c04d86abfaaf0790d7',
    messagingSenderId: '221351849206',
    projectId: 'instagram-clone-661d2',
    authDomain: 'instagram-clone-661d2.firebaseapp.com',
    storageBucket: 'instagram-clone-661d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY21z4Fgk51C1VhlbJBUSDvgkKHc6nzno',
    appId: '1:221351849206:android:20eedd67202443df0790d7',
    messagingSenderId: '221351849206',
    projectId: 'instagram-clone-661d2',
    storageBucket: 'instagram-clone-661d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6FQf05puX3Njfa12zXt5-StNUpSseBXI',
    appId: '1:221351849206:ios:de449ece457c7b6d0790d7',
    messagingSenderId: '221351849206',
    projectId: 'instagram-clone-661d2',
    storageBucket: 'instagram-clone-661d2.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
